### ISSUE TITLE
what license? 

### ISSUE THREAD

**Issue by trixpan** [martylamb/macnificent#1]
This fits like a glove to an opensource project I am working on but our code is Apache SL 2.0...

Would you mind defining a license?

**Comment by martylamb** [comment]
Hi trixpan - well done on finding this project - I've done essentially nothing to publicize it. :)

I will make a commit to this effect later, but the license will be Apache 2.0.  Glad it's helpful!

**Comment by trixpan** [comment]
give credit where credit is due.... Habemus Google. :-)

Thanks

**Comment by martylamb** [comment]
Just merged your PR - thanks!
